### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by srvoets** [Matthew17-21/Newegg-Shuffle#11]
First of all, thanks!  

I got it up and running, using proxies and anticaptcha.

I am using 33mail to create aliases that go into one (new) gmail inbox.

Im getting a lot of emails from newegg asking to verify email, while some (very few, in comparison) seem to have been registered without needing a verification.

Is this a by-product of the anti-captcha process?  Should I be attempting to verify these emails using the credentials from the log?  Something tells me doing so from my normal-ass IP will trigger a blacklist from newegg.

Also, in my accounts created log, I have several "unknown errors", with the other log saying 'send code over limit'

My programming/python knowledge is limited but I'd be happy to work on this further with anyone via discord.  I think the discord webhooks would be awesome, as well as outputting the log/accounts into CSV, using a spreadsheet to view this data would be a lot easier..  Im just not used to botting and dont wanna fuck myself up by using unverified accounts.

**Comment by Matthew17-21** [comment]
Hi!

> Im getting a lot of emails from newegg asking to verify email, while some (very few, in comparison) seem to have been registered without needing a verification.

> Is this a by-product of the anti-captcha process? Should I be attempting to verify these emails using the credentials from the log? Something tells me doing so from my normal-ass IP will trigger a blacklist from Newegg.

I personally haven't kept up with Newegg due to my schedule, so I really don't know if this is new or not BUT if you aren't using proxies, I **highly** **highly** suggest you do so. Proxies should definitely reduce the error.

> Also, in my accounts created log, I have several "unknown errors", with the other log saying 'send code over limit'

I just checked my old logs and don't think I had this response. Any other data included with the response?

> I think the discord webhooks would be awesome, as well as outputting the log/accounts into CSV, using a spreadsheet to view this data would be a lot easier.

I've gotten a few requests for webhooks, just no time unfortunately. The next time I come back to this project it'll most likely be for `1.2.0` which will include everything asked for + GUI + ease of installation, use & distribution. However, pull requests are always open!

**Comment by srvoets** [comment]
I am using proxies from oculus proxies, along with anticaptcha.

Heres the full error log:

`{
  "Result": "SendCodeOverLimit",
  "MessageEntitys": [
    {
      "MessageCode": "SendCodeOverLimit",
      "Description": "You have reached maximum number of attempts. Please try again later.",
      "MessageDatas": null
    }
  ]
}
`
